git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never
  
  # Auto fetch changes
  autoFetch: true
  fetchAll: true
  
  # Auto refresh and stage resolved conflicts
  autoRefresh: true
  autoStageResolvedConflicts: true
  
  # Commit settings
  commit:
    signOff: false
    wrapCommitMessageAt: 72

  # Log display settings
  log:
    showGraph: true
    order: 'topo-order'

os:
  edit: 'nvim {{filename}}'
  editAtLine: 'nvim +{{line}} {{filename}}'
  editAtLineAndWait: 'nvim +{{line}} {{filename}}'
  editInTerminal: true
  openDirInEditor: 'nvim {{dir}}'

gui:
  # Show file tree as a side panel
  showFileTree: true
  
  # Theme settings
  theme:
    activeBorderColor:
      - green
      - bold
    inactiveBorderColor:
      - white
    selectedLineBgColor:
      - blue
    defaultFgColor:
      - default
